export const mockWorkOrders = [
  {
    clientWorkOrderID: 1001,
    workOrderNumber: "WO-2024-001",
    description: "HVAC system not cooling properly in main office",
    categoryID: 1,
    categoryName: "HVAC",
    subcategoryID: 101,
    subcategoryName: "Air Conditioning",
    locationName: "Main Office - Floor 3",
    clientID: 501,
    clientName: "Acme Corporation",
    assetDescription: "Carrier Rooftop Unit - 25 Ton",
    assetID: 2001,
    assetNumber: "HVAC-RTU-003",
    problemTypeID: 301,
    problemTypeName: "No Cooling",
    reportedDate: "2024-11-20T09:30:00Z",
    siteCode: "SITE-001",
    siteID: 401,
    siteName: "Downtown Office Complex",
    updatedDate: "2024-11-27T14:22:00Z",
    workOrderStatusGroupID: 1,
    workOrderStatusGroupName: "In Progress",
    workOrderStatusID: 11,
    workOrderStatusName: "Technician Assigned",
    workOrderTypeID: 201,
    workOrderTypeName: "Corrective Maintenance",
    actionCount: 3,
    visitCount: 1,
    relatedWorkOrderCount: 0,
    documentsCount: 2,
    commentCount: 5,
  },
  {
    clientWorkOrderID: 1002,
    workOrderNumber: "WO-2024-002",
    description: "Leaking pipe in basement storage area",
    categoryID: 2,
    categoryName: "Plumbing",
    subcategoryID: 201,
    subcategoryName: "Water Supply",
    locationName: "Basement - Storage Room B",
    clientID: 501,
    clientName: "Acme Corporation",
    assetDescription: "Copper Water Line - 1 inch",
    assetID: 2002,
    assetNumber: "PLB-WL-045",
    problemTypeID: 302,
    problemTypeName: "Water Leak",
    reportedDate: "2024-11-25T16:45:00Z",
    siteCode: "SITE-001",
    siteID: 401,
    siteName: "Downtown Office Complex",
    updatedDate: "2024-11-27T10:15:00Z",
    workOrderStatusGroupID: 2,
    workOrderStatusGroupName: "Open",
    workOrderStatusID: 21,
    workOrderStatusName: "Awaiting Parts",
    workOrderTypeID: 202,
    workOrderTypeName: "Emergency Repair",
    actionCount: 2,
    visitCount: 1,
    relatedWorkOrderCount: 1,
    documentsCount: 1,
    commentCount: 3,
  },
  {
    clientWorkOrderID: 1003,
    workOrderNumber: "WO-2024-003",
    description: "Quarterly fire alarm system inspection",
    categoryID: 3,
    categoryName: "Fire Safety",
    subcategoryID: 301,
    subcategoryName: "Fire Alarm",
    locationName: "All Floors",
    clientID: 502,
    clientName: "TechStart Industries",
    assetDescription: "Simplex Fire Alarm Panel",
    assetID: 2003,
    assetNumber: "FIRE-PANEL-001",
    problemTypeID: 303,
    problemTypeName: "Scheduled Inspection",
    reportedDate: "2024-11-15T08:00:00Z",
    siteCode: "SITE-002",
    siteID: 402,
    siteName: "Industrial Park Building 5",
    updatedDate: "2024-11-26T17:30:00Z",
    workOrderStatusGroupID: 3,
    workOrderStatusGroupName: "Completed",
    workOrderStatusID: 31,
    workOrderStatusName: "Closed - Complete",
    workOrderTypeID: 203,
    workOrderTypeName: "Preventive Maintenance",
    actionCount: 1,
    visitCount: 1,
    relatedWorkOrderCount: 0,
    documentsCount: 4,
    commentCount: 2,
  },
  {
    clientWorkOrderID: 1004,
    workOrderNumber: "WO-2024-004",
    description: "Flickering lights in conference room",
    categoryID: 4,
    categoryName: "Electrical",
    subcategoryID: 401,
    subcategoryName: "Lighting",
    locationName: "Conference Room A",
    clientID: 501,
    clientName: "Acme Corporation",
    assetDescription: "LED Panel Lights - 2x4",
    assetID: 2004,
    assetNumber: "ELEC-LIGHT-012",
    problemTypeID: 304,
    problemTypeName: "Intermittent Power",
    reportedDate: "2024-11-27T11:20:00Z",
    siteCode: "SITE-001",
    siteID: 401,
    siteName: "Downtown Office Complex",
    updatedDate: "2024-11-27T11:20:00Z",
    workOrderStatusGroupID: 2,
    workOrderStatusGroupName: "Open",
    workOrderStatusID: 22,
    workOrderStatusName: "Unassigned",
    workOrderTypeID: 201,
    workOrderTypeName: "Corrective Maintenance",
    actionCount: 0,
    visitCount: 0,
    relatedWorkOrderCount: 0,
    documentsCount: 0,
    commentCount: 1,
  },
  {
    clientWorkOrderID: 1005,
    workOrderNumber: "WO-2024-005",
    description: "Elevator making unusual noise between floors 2-3",
    categoryID: 5,
    categoryName: "Elevators",
    subcategoryID: 501,
    subcategoryName: "Passenger Elevator",
    locationName: "Elevator Bank 1 - Car B",
    clientID: 503,
    clientName: "Medical Plaza Associates",
    assetDescription: "Otis Hydraulic Elevator",
    assetID: 2005,
    assetNumber: "ELEV-B-001",
    problemTypeID: 305,
    problemTypeName: "Unusual Noise",
    reportedDate: "2024-11-24T13:15:00Z",
    siteCode: "SITE-003",
    siteID: 403,
    siteName: "Medical Plaza West",
    updatedDate: "2024-11-27T09:45:00Z",
    workOrderStatusGroupID: 1,
    workOrderStatusGroupName: "In Progress",
    workOrderStatusID: 12,
    workOrderStatusName: "On Site",
    workOrderTypeID: 201,
    workOrderTypeName: "Corrective Maintenance",
    actionCount: 4,
    visitCount: 2,
    relatedWorkOrderCount: 2,
    documentsCount: 3,
    commentCount: 8,
  },
];
